### ISSUE TITLE
TOC implementation

### ISSUE THREAD

**Issue by CieNTi** [nazar-pc/php-markdown-next#4]
Are you planning to include TOC generation into this lib?

Thanks!

**Comment by nazar-pc** [comment]
Can you explain abbreviation TOC?

**Comment by GrahamCampbell** [comment]
"TOC" => "table of contents".

**Comment by nazar-pc** [comment]
I didn't have such plans.
But I'll be happy to merge pull request.

**Comment by metude** [comment]
In case of anyone wants to use it or create a pull request http://www.kryogenix.org/code/browser/generated-toc/

**Comment by nazar-pc** [comment]
Well, but that realization as I understand is written in JavaScript, but this library in PHP.

**Comment by metude** [comment]
I know, but it works well and may be someone import same logic.

**Comment by CieNTi** [comment]
That's nice! And I just forked from a guy who improved it. I'm trying to get some time to develop the markdown one.
